In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

In [25]:
df = pd.read_csv(r"D://Guvi//Projects//mini//Amazon Delivery Time Prediction//Amazon_delivery_time_prediction//data//raw//amazon_delivery.csv")
df.head()

,Order_ID,Agent_Age,Agent_Rating,Store_Latitude,Store_Longitude,Drop_Latitude,Drop_Longitude,Order_Date,Order_Time,Pickup_Time,Weather,Traffic,Vehicle,Area,Delivery_Time,Category
0,ialx566343618,37,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,11:30:00,11:45:00,Sunny,High,motorcycle,Urban,120,Clothing
1,akqg208421122,34,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,19:45:00,19:50:00,Stormy,Jam,scooter,Metropolitian,165,Electronics
2,njpu434582536,23,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,08:30:00,08:45:00,Sandstorms,Low,motorcycle,Urban,130,Sports
3,rjto796129700,38,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,18:00:00,18:10:00,Sunny,Medium,motorcycle,Metropolitian,105,Cosmetics
4,zguw716275638,32,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,13:30:00,13:45:00,Cloudy,High,scooter,Metropolitian,150,Toys

In [26]:
print(df.shape)

(43739, 16)

In [27]:
df.columns

Index(['Order_ID', 'Agent_Age', 'Agent_Rating', 'Store_Latitude',
       'Store_Longitude', 'Drop_Latitude', 'Drop_Longitude', 'Order_Date',
       'Order_Time', 'Pickup_Time', 'Weather', 'Traffic', 'Vehicle', 'Area',
       'Delivery_Time', 'Category'],
      dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43739 entries, 0 to 43738
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         43739 non-null  object
 1   Agent_Age        43739 non-null  int64
 2   Agent_Rating     43685 non-null  float64
 3   Store_Latitude   43739 non-null  float64
 4   Store_Longitude  43739 non-null  float64
 5   Drop_Latitude    43739 non-null  float64
 6   Drop_Longitude   43739 non-null  float64
 7   Order_Date       43739 non-null  object
 8   Order_Time       43739 non-null  object
 9   Pickup_Time      43739 non-null  object
 10  Weather          43648 non-null  object
 11  Traffic          43739 non-null  object
 12  Vehicle          43739 non-null  object
 13  Area             43739 non-null  object
 14  Delivery_Time    43739 non-null  int64
 15  Category         43739 non-null  object
dtypes: float64(5), int64(2), object(9)
memory usage: 5.3+ MB

In [29]:
df.describe()

,Agent_Age,Agent_Rating,Store_Latitude,Store_Longitude,Drop_Latitude,Drop_Longitude,Delivery_Time
count,43739.000000,43685.000000,43739.000000,43739.000000,43739.000000,43739.000000,43739.000000
mean,29.567137,4.633780,17.210960,70.661177,17.459031,70.821842,124.905645
std,5.815155,0.334716,7.764225,21.475005,7.342950,21.153148,51.915451
min,15.000000,1.000000,-30.902872,-88.366217,0.010000,0.010000,10.000000
25%,25.000000,4.500000,12.933298,73.170283,12.985996,73.280000,90.000000
50%,30.000000,4.700000,18.551440,75.898497,18.633626,76.002574,125.000000
75%,35.000000,4.900000,22.732225,78.045359,22.785049,78.104095,160.000000
max,50.000000,6.000000,30.914057,88.433452,31.054057,88.563452,270.000000

## Handle Missing Values

In [30]:
df.isnull()

,Order_ID,Agent_Age,Agent_Rating,Store_Latitude,Store_Longitude,Drop_Latitude,Drop_Longitude,Order_Date,Order_Time,Pickup_Time,Weather,Traffic,Vehicle,Area,Delivery_Time,Category
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43734,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
43735,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
43736,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
43737,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
43738,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [31]:
df.isnull().sum()

Order_ID            0
Agent_Age           0
Agent_Rating       54
Store_Latitude      0
Store_Longitude     0
Drop_Latitude       0
Drop_Longitude      0
Order_Date          0
Order_Time          0
Pickup_Time         0
Weather            91
Traffic             0
Vehicle             0
Area                0
Delivery_Time       0
Category            0
dtype: int64

In [ ]:
# # Numerical columns
# num_cols = df.select_dtypes(include=np.number).columns
# df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# # Categorical columns
# cat_cols = df.select_dtypes(exclude=np.number).columns
# df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

In [32]:
df['Agent_Rating'].fillna(df['Agent_Rating'].median(), inplace=True)
df['Weather'].fillna("Unknown", inplace=True)

C:\Users\shubh\AppData\Local\Temp\ipykernel_7036\2362605863.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Agent_Rating'].fillna(df['Agent_Rating'].median(), inplace=True)
C:\Users\shubh\AppData\Local\Temp\ipykernel_7036\2362605863.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Weather'].fillna("Unknown", inplace=True)

In [33]:
df.isnull().sum()

Order_ID           0
Agent_Age          0
Agent_Rating       0
Store_Latitude     0
Store_Longitude    0
Drop_Latitude      0
Drop_Longitude     0
Order_Date         0
Order_Time         0
Pickup_Time        0
Weather            0
Traffic            0
Vehicle            0
Area               0
Delivery_Time      0
Category           0
dtype: int64

## Remove Duplicates

In [34]:
df.duplicated().sum()
# df = df.drop_duplicates()

np.int64(0)

## Outlier Detection & Treatment

In [35]:
num_cols = df.select_dtypes(include=np.number).columns
num_cols = num_cols.drop('Delivery_Time')

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    # df = df[(df[col] >= lower) & (df[col] <= upper)]
    df[col] = df[col].clip(lower, upper)

In [36]:
df

,Order_ID,Agent_Age,Agent_Rating,Store_Latitude,Store_Longitude,Drop_Latitude,Drop_Longitude,Order_Date,Order_Time,Pickup_Time,Weather,Traffic,Vehicle,Area,Delivery_Time,Category
0,ialx566343618,37,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,11:30:00,11:45:00,Sunny,High,motorcycle,Urban,120,Clothing
1,akqg208421122,34,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,19:45:00,19:50:00,Stormy,Jam,scooter,Metropolitian,165,Electronics
2,njpu434582536,23,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,08:30:00,08:45:00,Sandstorms,Low,motorcycle,Urban,130,Sports
3,rjto796129700,38,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,18:00:00,18:10:00,Sunny,Medium,motorcycle,Metropolitian,105,Cosmetics
4,zguw716275638,32,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,13:30:00,13:45:00,Cloudy,High,scooter,Metropolitian,150,Toys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43734,jlxf819993117,30,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,11:35:00,11:45:00,Windy,High,motorcycle,Metropolitian,160,Home
43735,aevx342135787,21,4.6,0.000000,65.857669,0.070000,66.043858,2022-02-16,19:55:00,20:10:00,Windy,Jam,motorcycle,Metropolitian,180,Jewelry
43736,xnek760674819,30,4.9,13.022394,80.242439,13.052394,80.272439,2022-03-11,23:50:00,00:05:00,Cloudy,Low,scooter,Metropolitian,80,Home
43737,cynl434665991,20,4.7,11.001753,76.986241,11.041753,77.026241,2022-03-07,13:35:00,13:40:00,Cloudy,High,motorcycle,Metropolitian,130,Kitchen
43738,nsyz997960170,23,4.9,23.351058,85.325731,23.431058,85.340238,2022-03-02,17:10:00,17:15:00,Fog,Medium,scooter,Metropolitian,180,Cosmetics

## Feature Encoding

In [ ]:
# # Drop ID
# df = df.drop('Order_ID', axis=1)

# # Identify categorical columns
# cat_cols = df.select_dtypes(exclude=np.number).columns

# binary_cols = [col for col in cat_cols if df[col].nunique() == 2]
# multi_cols = [col for col in cat_cols if df[col].nunique() > 2]

# # Label Encoding
# le = LabelEncoder()
# for col in binary_cols:
#     df[col] = le.fit_transform(df[col])

# # One-Hot Encoding
# df = pd.get_dummies(df, columns=multi_cols, drop_first=True)

In [38]:
df

,Agent_Age,Agent_Rating,Store_Latitude,Store_Longitude,Drop_Latitude,Drop_Longitude,Delivery_Time,Order_Date_2022-02-12,Order_Date_2022-02-13,Order_Date_2022-02-14,...,Category_Home,Category_Jewelry,Category_Kitchen,Category_Outdoors,Category_Pet Supplies,Category_Shoes,Category_Skincare,Category_Snacks,Category_Sports,Category_Toys
0,37,4.9,22.745049,75.892471,22.765049,75.912471,120,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,34,4.5,12.913041,77.683237,13.043041,77.813237,165,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,23,4.4,12.914264,77.678400,12.924264,77.688400,130,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,38,4.7,11.003669,76.976494,11.053669,77.026494,105,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,32,4.6,12.972793,80.249982,13.012793,80.289982,150,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43734,30,4.8,26.902328,75.794257,26.912328,75.804257,160,False,False,False,...,True,False,False,False,False,False,False,False,False,False
43735,21,4.6,0.000000,65.857669,0.070000,66.043858,180,False,False,False,...,False,True,False,False,False,False,False,False,False,False
43736,30,4.9,13.022394,80.242439,13.052394,80.272439,80,False,False,False,...,True,False,False,False,False,False,False,False,False,False
43737,20,4.7,11.001753,76.986241,11.041753,77.026241,130,False,False,False,...,False,False,True,False,False,False,False,False,False,False
43738,23,4.9,23.351058,85.325731,23.431058,85.340238,180,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Train-Test Split

In [ ]:
# X = df.drop('Delivery_Time', axis=1)
# y = df['Delivery_Time']

In [ ]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42
# )

## Feature Scaling

In [ ]:
# num_cols = X_train.select_dtypes(include=np.number).columns

# scaler = StandardScaler()

# X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
# X_test[num_cols] = scaler.transform(X_test[num_cols])

In [ ]:
# import joblib
# joblib.dump(scaler, "D://Guvi//Projects//mini//Amazon Delivery Time Prediction//Amazon_delivery_time_prediction//models//scaler.pkl")

### Save Preprocessed Data

In [ ]:
# file_path = r"D://Guvi//Projects//mini//Amazon Delivery Time Prediction//Amazon_delivery_time_prediction//data//processed/"

In [ ]:
X_train.to_csv(file_path+"X_train.csv", index=False)
# X_test.to_csv(file_path+"X_test.csv", index=False)
print("Data set saved")